SELECT
    c.TABLE_NAME AS table_name,
    GROUP_CONCAT(DISTINCT c.COLUMN_NAME ORDER BY c.ORDINAL_POSITION SEPARATOR ', ') AS relevant_columns,
    MAX(t.TABLE_ROWS) AS estimated_rows
FROM information_schema.COLUMNS c
JOIN information_schema.TABLES t
  ON t.TABLE_SCHEMA = c.TABLE_SCHEMA
 AND t.TABLE_NAME = c.TABLE_NAME
WHERE c.TABLE_SCHEMA = DATABASE()
  AND (
      c.COLUMN_NAME IN ('CUSTOMER_ID', 'ROUTE_ID', 'SECTOR_ID')
      OR LOWER(c.COLUMN_NAME) LIKE '%broker%'
      OR LOWER(c.COLUMN_NAME) LIKE '%pickup%route%'
      OR LOWER(c.COLUMN_NAME) LIKE '%route%pickup%'
  )
GROUP BY c.TABLE_NAME
HAVING SUM(c.COLUMN_NAME = 'CUSTOMER_ID') > 0
    OR SUM(c.COLUMN_NAME = 'ROUTE_ID') > 0
    OR SUM(c.COLUMN_NAME = 'SECTOR_ID') > 0
ORDER BY
    (SUM(c.COLUMN_NAME = 'CUSTOMER_ID') > 0
     AND (SUM(c.COLUMN_NAME = 'ROUTE_ID') > 0 OR SUM(c.COLUMN_NAME = 'SECTOR_ID') > 0)) DESC,
    c.TABLE_NAME;
