SELECT
    DATE_HEURE,
    SORTING_DATE,
    CONVEYED_PARCELS,
    UNIQUE_PARCELS,
    NC_MANUAL,
    NC_AUTOMATIC,
    SMALL_PARCELS,
    NC_MANUAL3,
    WEIGHT_ERRORS,
    SPACING_SORTING_ERRORS,
    CHUTES_PLEINES,
    EMPLOYEES_NBR
FROM conveyor_hourlystats
WHERE DEPOT_ID = 1
  AND SORTING_DATE = '2026-07-12'
ORDER BY DATE_HEURE;
