WITH parcel_rollup AS (
    SELECT
        ph.PARCEL_ID,
        COUNT(*) AS ROUTING_EVENTS,
        COUNT(DISTINCT COALESCE(ph.SOURCE_ID, 0)) AS DISTINCT_LINES_OR_SOURCES,
        MIN(ph.DATE_INSERT) AS FIRST_EVENT,
        MAX(ph.DATE_INSERT) AS LAST_EVENT
    FROM parcel_history PARTITION (p2026) AS ph
    WHERE ph.DATE_INSERT >= '2026-07-12 17:00:00'
      AND ph.DATE_INSERT <  '2026-07-13 08:00:00'
      AND ph.DEPOT_ID = 1
      AND ph.SOURCE_TYPE = 200
      AND (ph.SOURCE_ID IS NULL OR ph.SOURCE_ID IN (1, 3))
      AND ph.PARCEL_ID IS NOT NULL
    GROUP BY ph.PARCEL_ID
)
SELECT
    COUNT(*) AS UNIQUE_ROUTED_PARCELS,
    SUM(ROUTING_EVENTS) AS ROUTING_EVENTS,
    SUM(ROUTING_EVENTS > 1) AS PARCELS_WITH_MULTIPLE_ROUTING_EVENTS,
    SUM(ROUTING_EVENTS - 1) AS EXTRA_ROUTING_EVENTS,
    ROUND(100.0 * SUM(ROUTING_EVENTS > 1) / NULLIF(COUNT(*), 0), 2) AS MULTI_EVENT_PARCEL_RATE_PCT,
    SUM(DISTINCT_LINES_OR_SOURCES > 1) AS PARCELS_SEEN_ON_MULTIPLE_LINES_OR_SOURCES,
    MAX(ROUTING_EVENTS) AS MAX_ROUTING_EVENTS_FOR_ONE_PARCEL
FROM parcel_rollup;
