SELECT
    DATE_FORMAT(ph.DATE_INSERT, '%Y-%m-%d %H:00:00') AS EVENT_HOUR,
    ph.SOURCE_TYPE,
    ph.SOURCE_ID,
    COUNT(*) AS EVENT_COUNT,
    COUNT(DISTINCT ph.PARCEL_ID) AS UNIQUE_PARCELS
FROM parcel_history PARTITION (p2026) AS ph
WHERE ph.DATE_INSERT >= '2026-07-12 12:00:00'
  AND ph.DATE_INSERT <  '2026-07-13 12:00:00'
  AND ph.DEPOT_ID = 1
  AND ph.SOURCE_TYPE BETWEEN 200 AND 205
GROUP BY EVENT_HOUR, ph.SOURCE_TYPE, ph.SOURCE_ID
ORDER BY EVENT_HOUR, ph.SOURCE_TYPE, ph.SOURCE_ID;
