SELECT
    ph.SOURCE_TYPE,
    st.SOURCE_TYPE_FR,
    COUNT(*) AS EVENT_COUNT,
    COUNT(DISTINCT ph.PARCEL_ID) AS UNIQUE_PARCELS
FROM parcel_history PARTITION (p2026) AS ph
LEFT JOIN parcel_history_source_type AS st
    ON st.SOURCE_TYPE = ph.SOURCE_TYPE
WHERE ph.DATE_INSERT >= '2026-07-12 17:00:00'
  AND ph.DATE_INSERT <  '2026-07-13 08:00:00'
  AND ph.DEPOT_ID = 1
  AND ph.SOURCE_TYPE BETWEEN 201 AND 205
GROUP BY ph.SOURCE_TYPE, st.SOURCE_TYPE_FR
ORDER BY ph.SOURCE_TYPE;
