SELECT
    ph.SOURCE_ID AS LINE_OR_SOURCE_ID,
    ph.CHUTE_NO,
    COUNT(*) AS EVENT_COUNT,
    COUNT(DISTINCT ph.PARCEL_ID) AS UNIQUE_PARCELS
FROM parcel_history PARTITION (p2026) AS ph
WHERE ph.DATE_INSERT >= '2026-07-12 17:00:00'
  AND ph.DATE_INSERT <  '2026-07-13 08:00:00'
  AND ph.DEPOT_ID = 1
  AND ph.SOURCE_TYPE = 200
  AND (ph.SOURCE_ID IS NULL OR ph.SOURCE_ID IN (1, 3))
GROUP BY ph.SOURCE_ID, ph.CHUTE_NO
ORDER BY EVENT_COUNT DESC
LIMIT 100;
