SELECT
    d.DEPOTNUMBER,
    d.DEPOTNAME,
    d.DEPOTNAMESHORT,
    d.DEPOT_SHORT_LABEL,
    d.DEPOT_ABREV,
    d.HAS_CONVEYOR,
    d.CONV_MIN_START_HOUR,
    d.CONV_MAX_END_HOUR,
    c.CONVEYOR_ID,
    c.LOCATION_NAME,
    c.DATATYPE,
    c.SOURCE_ID,
    c.ENABLED,
    c.VERSION,
    cl.CONVEYOR_NAME
FROM depot AS d
LEFT JOIN conveyor AS c
    ON c.DEPOT_ID = d.DEPOTNUMBER
LEFT JOIN conveyor_list AS cl
    ON cl.CONVEYOR_ID = c.CONVEYOR_ID
WHERE d.DEPOTNAME LIKE '%hubert%'
   OR d.DEPOTNAMESHORT LIKE '%hubert%'
   OR d.VILLE LIKE '%hubert%'
ORDER BY d.DEPOTNUMBER, c.CONVEYOR_ID;
