SELECT
    ph.SOURCE_TYPE,
    st.SOURCE_TYPE_FR,
    ph.SOURCE_ID,
    COUNT(*) AS EVENT_COUNT,
    COUNT(DISTINCT ph.PARCEL_HISTORY_ID) AS DISTINCT_HISTORY_ROWS,
    COUNT(DISTINCT ph.PARCEL_ID) AS DISTINCT_PARCEL_IDS,
    MIN(ph.DATE_INSERT) AS FIRST_EVENT,
    MAX(ph.DATE_INSERT) AS LAST_EVENT
FROM parcel_history PARTITION (p2026) AS ph
LEFT JOIN parcel_history_source_type AS st
    ON st.SOURCE_TYPE = ph.SOURCE_TYPE
WHERE ph.DATE_INSERT >= '2026-07-12 00:00:00'
  AND ph.DATE_INSERT <  '2026-07-13 00:00:00'
  AND ph.DEPOT_ID = 1
  AND ph.SOURCE_TYPE BETWEEN 200 AND 205
GROUP BY ph.SOURCE_TYPE, st.SOURCE_TYPE_FR, ph.SOURCE_ID
ORDER BY ph.SOURCE_TYPE, ph.SOURCE_ID;
