SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    COLUMN_TYPE,
    COLUMN_KEY,
    COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'shipment'
  AND (
      COLUMN_NAME LIKE '%DEPOT%'
      OR COLUMN_NAME LIKE '%ROUTE%'
      OR COLUMN_NAME LIKE '%POSTAL%'
      OR COLUMN_NAME LIKE '%PROVINCE%'
      OR COLUMN_NAME LIKE '%CITY%'
  )
ORDER BY ORDINAL_POSITION;
