SELECT
    s.CUSTOMER_ID,
    COUNT(DISTINCT s.ID) AS shipments,
    SUM(s.PARCEL_NB) AS parcel_nb,
    COUNT(DISTINCT p.PARCEL_ID) AS parcel_rows_by_shipping,
    COUNT(CASE WHEN p.LENGTH > 0 AND p.WIDTH > 0 AND p.HEIGHT > 0 THEN 1 END) AS valid_dimensions,
    COUNT(CASE WHEN p.WEIGHT > 0 THEN 1 END) AS valid_weights,
    AVG(CASE WHEN p.LENGTH > 0 AND p.WIDTH > 0 AND p.HEIGHT > 0 THEN p.LENGTH * p.WIDTH * p.HEIGHT END) AS avg_volume,
    AVG(CASE WHEN p.WEIGHT > 0 THEN p.WEIGHT END) AS avg_weight
FROM shipment s
LEFT JOIN parcel p
  ON p.SHIPPING_ID = s.SHIPPING_ID
 AND p.EXP_DATE = s.EXP_DATE
WHERE s.CUSTOMER_ID IN (112008, 303523, 154786, 303598)
  AND s.INSERT_DATE >= '2026-07-27'
  AND s.INSERT_DATE < '2026-08-26'
GROUP BY s.CUSTOMER_ID;
