SELECT DEPOTNUMBER,DEPOTNAME,DEPOT_SHORT_LABEL,DASHBOARD_ACTIVE,HAS_CONVEYOR,DASHBOARD_ORDER
FROM depot
WHERE DEPOTNUMBER>0 AND NULLIF(TRIM(DEPOTNAME),'') IS NOT NULL
ORDER BY COALESCE(DASHBOARD_ORDER,9999),DEPOTNAME;
