SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'customer'
  AND (LOWER(COLUMN_NAME) LIKE '%route%' OR LOWER(COLUMN_NAME) LIKE '%pickup%' OR LOWER(COLUMN_NAME) LIKE '%pu_%')
ORDER BY ORDINAL_POSITION;
