SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('parcel', 'shipment')
  AND (
      LOWER(COLUMN_NAME) LIKE '%weight%'
      OR LOWER(COLUMN_NAME) LIKE '%poids%'
      OR LOWER(COLUMN_NAME) LIKE '%length%'
      OR LOWER(COLUMN_NAME) LIKE '%width%'
      OR LOWER(COLUMN_NAME) LIKE '%height%'
      OR LOWER(COLUMN_NAME) LIKE '%dimension%'
      OR LOWER(COLUMN_NAME) LIKE '%volume%'
      OR LOWER(COLUMN_NAME) LIKE '%cub%'
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;
