SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'customer'
  AND (
      LOWER(COLUMN_NAME) LIKE '%lat%'
      OR LOWER(COLUMN_NAME) LIKE '%lon%'
      OR LOWER(COLUMN_NAME) LIKE '%long%'
      OR LOWER(COLUMN_NAME) LIKE '%postal%'
      OR LOWER(COLUMN_NAME) LIKE '%city%'
      OR LOWER(COLUMN_NAME) LIKE '%province%'
      OR LOWER(COLUMN_NAME) LIKE '%address%'
  )
ORDER BY ORDINAL_POSITION;
