SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'customer'
  AND (
      LOWER(COLUMN_NAME) LIKE '%activ%'
      OR LOWER(COLUMN_NAME) LIKE '%status%'
      OR LOWER(COLUMN_NAME) LIKE '%disable%'
      OR LOWER(COLUMN_NAME) LIKE '%close%'
      OR LOWER(COLUMN_NAME) LIKE '%delete%'
  )
ORDER BY ORDINAL_POSITION;
