SELECT COLUMN_NAME, DATA_TYPE
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name = 'customer'
  AND (COLUMN_NAME LIKE '%ADDRESS%'
    OR COLUMN_NAME LIKE '%ADRESS%'
    OR COLUMN_NAME LIKE '%CITY%'
    OR COLUMN_NAME LIKE '%VILLE%'
    OR COLUMN_NAME LIKE '%POSTAL%'
    OR COLUMN_NAME LIKE '%ZIP%')
ORDER BY ORDINAL_POSITION;
