SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'parcel'
  AND (COLUMN_NAME IN ('PARCEL_ID','SHIPPING_ID','WEIGHT','LENGTH','WIDTH','HEIGHT','CUBING') OR COLUMN_NAME LIKE '%DATE%')
ORDER BY ORDINAL_POSITION;
