SELECT DISTINCT
    c.CUSTOMER_ID AS customer_id,
    c.NAME AS client,
    c.LATITUDE AS latitude,
    c.LONGITUDE AS longitude
FROM customer c
WHERE c.ACTIVE = 1
  AND c.LATITUDE IS NOT NULL
  AND c.LONGITUDE IS NOT NULL
  AND c.LATITUDE BETWEEN 40 AND 50
  AND c.LONGITUDE BETWEEN -80 AND -65
  AND LOWER(c.NAME) NOT LIKE '%nationex%';
