SELECT
    ROUTE_DATE,
    ROUTE_ID,
    CUSTOMER_ID,
    PICKUP_ID,
    COUNT(*) AS rows_per_pickup,
    COUNT(DISTINCT FORECASTED_ARRIVAL_TIME) AS distinct_forecast_times,
    MIN(FORECASTED_ARRIVAL_TIME) AS earliest_forecast_time,
    MAX(FORECASTED_ARRIVAL_TIME) AS latest_forecast_time,
    MAX(UPDATE_DATE) AS latest_update
FROM live_route
WHERE CUSTOMER_ID = 158563
  AND ROUTE_DATE >= CURRENT_DATE - INTERVAL 30 DAY
  AND ROUTE_DATE < CURRENT_DATE + INTERVAL 1 DAY
  AND PICKUP_ID IS NOT NULL
GROUP BY ROUTE_DATE, ROUTE_ID, CUSTOMER_ID, PICKUP_ID
ORDER BY ROUTE_DATE DESC, PICKUP_ID
LIMIT 100;
