SELECT ph.PARCEL_HISTORY_ID,ph.PARCEL_ID,ph.DATE_LIV,ph.EXCEPTION,
       e.TXTFRENCH,e.EX_NAME_FR,se.DESCRIPTION_FR sub_description,
       ph.USER_ID,nu.FIRSTNAME,nu.LASTNAME,
       ph.TPSL,tr.ROUTE_NAME,tr.ROUTE_DRIVER_NAME,tr.USERNAME,
       ph.SOURCE_TYPE,ph.SOURCE_ID,psi.SOURCE_DESCRIPTION,
       ph.CONTACT,ph.REASON,ph.DEPOT_ID,d.DEPOTNAME,ph.VOID
FROM parcel_history PARTITION (p2026) ph
LEFT JOIN exceptions e ON e.CODE=ph.EXCEPTION
LEFT JOIN sub_exceptions se ON se.SUB_EXCEPTION_ID=ph.SUB_EXCEPTION_ID
LEFT JOIN nat_user nu ON nu.NAT_USER_ID=ph.USER_ID
LEFT JOIN route tr ON tr.ROUTE_ID=ph.TPSL
LEFT JOIN parcel_history_source_id psi ON psi.SOURCE_ID=ph.SOURCE_ID
LEFT JOIN depot d ON d.DEPOTNUMBER=ph.DEPOT_ID
WHERE ph.PARCEL_ID IN (51834803664,85030364101,19016697901)
ORDER BY ph.DATE_LIV DESC,ph.PARCEL_HISTORY_ID DESC;
