SELECT c.TABLE_NAME,c.COLUMN_NAME,c.DATA_TYPE
FROM information_schema.COLUMNS c
JOIN information_schema.TABLES t
  ON t.TABLE_SCHEMA=c.TABLE_SCHEMA AND t.TABLE_NAME=c.TABLE_NAME
WHERE c.TABLE_SCHEMA=DATABASE()
  AND (
    c.TABLE_NAME REGEXP 'exception|event|status|user|tpsl'
    OR c.COLUMN_NAME REGEXP 'EXCEPTION|DESCRIPTION|LABEL|USERNAME|USER_NAME|TPSL'
  )
ORDER BY c.TABLE_NAME,c.ORDINAL_POSITION;
