SELECT ph.PARCEL_ID,ph.PARCEL_INTERNAL_ID,ph.SHIPPING_ID,ph.CONSOL_ID,ph.MANIFEST_ID,ph.EXP_DATE,
       p.SHIPMENT_INTERNAL_ID,p.SHIPPING_ID parcel_shipping_id,p.EXP_DATE parcel_exp_date,
       s.DEST_SECTOR_ID,s.DEST_ROUTE_ID,s.DEST_CITY,s.DEST_PROVINCE
FROM parcel_history PARTITION (p2026) ph
LEFT JOIN parcel p ON p.ID=ph.PARCEL_INTERNAL_ID
LEFT JOIN shipment s ON s.SHIPPING_ID=ph.SHIPPING_ID AND s.EXP_DATE=ph.EXP_DATE
WHERE ph.DEPOT_ID=2 AND ph.EXCEPTION=25 AND ph.SOURCE_TYPE=900
  AND COALESCE(ph.VOID,0)=0
  AND ph.DATE_LIV>=CURDATE() AND ph.DATE_LIV<CURDATE()+INTERVAL 1 DAY
ORDER BY ph.DATE_LIV
LIMIT 100;
