SELECT ph.EXCEPTION,ph.SOURCE_TYPE,ph.SOURCE_ID,
       COUNT(*) events,COUNT(DISTINCT ph.PARCEL_ID) parcels
FROM parcel_history PARTITION (p2026) ph
WHERE ph.DEPOT_ID=2
  AND ph.EXCEPTION IN (25,903,904)
  AND COALESCE(ph.VOID,0)=0
  AND ph.PARCEL_ID IS NOT NULL AND ph.PARCEL_ID<>0
  AND ph.DATE_INSERT>=CURDATE()-INTERVAL 1 DAY
  AND ph.DATE_INSERT<CURDATE()+INTERVAL 1 DAY
  AND ph.DATE_LIV>=CURDATE() AND ph.DATE_LIV<CURDATE()+INTERVAL 1 DAY
GROUP BY ph.EXCEPTION,ph.SOURCE_TYPE,ph.SOURCE_ID
ORDER BY ph.EXCEPTION,events DESC;

WITH code25 AS (
    SELECT ph.PARCEL_ID,MAX(ph.SHIPPING_ID) shipping_id,MAX(ph.EXP_DATE) exp_date
    FROM parcel_history PARTITION (p2026) ph
    WHERE ph.DEPOT_ID=2 AND ph.EXCEPTION=25
      AND COALESCE(ph.VOID,0)=0
      AND ph.PARCEL_ID IS NOT NULL AND ph.PARCEL_ID<>0
      AND ph.DATE_INSERT>=CURDATE()-INTERVAL 1 DAY
      AND ph.DATE_INSERT<CURDATE()+INTERVAL 1 DAY
      AND ph.DATE_LIV>=CURDATE() AND ph.DATE_LIV<CURDATE()+INTERVAL 1 DAY
    GROUP BY ph.PARCEL_ID
)
SELECT s.DEST_ROUTE_ID,r.START_DEPOT_ID,r.END_DEPOT_ID,
       nr.DEPOT_ID nat_route_depot,si.DEPOTNUMBER sector_depot,
       COUNT(*) parcels
FROM code25 cp
LEFT JOIN shipment s ON s.SHIPPING_ID=cp.shipping_id AND s.EXP_DATE=cp.exp_date
LEFT JOIN route r ON r.ROUTE_ID=s.DEST_ROUTE_ID
LEFT JOIN nat_route nr ON nr.ROUTE_ID=s.DEST_ROUTE_ID
LEFT JOIN sector_info si ON si.SECTOR_ID=s.DEST_SECTOR_ID
GROUP BY s.DEST_ROUTE_ID,r.START_DEPOT_ID,r.END_DEPOT_ID,nr.DEPOT_ID,si.DEPOTNUMBER
ORDER BY parcels DESC,s.DEST_ROUTE_ID;
