SELECT
    ph.EXCEPTION,
    ph.SOURCE_TYPE,
    ph.SOURCE_ID,
    COUNT(*) AS passages,
    COUNT(DISTINCT ph.PARCEL_ID) AS colis_uniques,
    MIN(ph.DATE_LIV) AS premier,
    MAX(ph.DATE_LIV) AS dernier
FROM parcel_history PARTITION (p2026) ph
WHERE ph.DEPOT_ID = 2
  AND ph.EXCEPTION IN (901, 903, 904, 25)
  AND COALESCE(ph.VOID, 0) = 0
  AND ph.PARCEL_ID IS NOT NULL
  AND ph.PARCEL_ID <> 0
  AND ph.DATE_INSERT >= CURDATE() - INTERVAL 4 DAY
  AND ph.DATE_LIV >= CURDATE() - INTERVAL 3 DAY
  AND ph.DATE_LIV < CURDATE() + INTERVAL 1 DAY
GROUP BY ph.EXCEPTION, ph.SOURCE_TYPE, ph.SOURCE_ID
ORDER BY ph.EXCEPTION, passages DESC;
