WITH code25 AS (
    SELECT DISTINCT ph.PARCEL_ID
    FROM parcel_history PARTITION (p2026) ph
    WHERE ph.DEPOT_ID=2 AND ph.EXCEPTION=25
      AND COALESCE(ph.VOID,0)=0
      AND ph.PARCEL_ID IS NOT NULL AND ph.PARCEL_ID<>0
      AND ph.DATE_INSERT>=CURDATE()-INTERVAL 1 DAY
      AND ph.DATE_INSERT<CURDATE()+INTERVAL 1 DAY
      AND ph.DATE_LIV>=CURDATE() AND ph.DATE_LIV<CURDATE()+INTERVAL 1 DAY
),
first_qc_ranked AS (
    SELECT ph.PARCEL_ID,ph.PARCEL_HISTORY_ID,ph.DATE_LIV,
           ROW_NUMBER() OVER(PARTITION BY ph.PARCEL_ID ORDER BY ph.DATE_LIV,ph.PARCEL_HISTORY_ID) rn
    FROM parcel_history PARTITION (p2026) ph
    JOIN code25 c ON c.PARCEL_ID=ph.PARCEL_ID
    WHERE ph.DEPOT_ID=2 AND COALESCE(ph.VOID,0)=0
),
first_qc AS (
    SELECT PARCEL_ID,PARCEL_HISTORY_ID,DATE_LIV FROM first_qc_ranked WHERE rn=1
),
prior_ranked AS (
    SELECT ph.PARCEL_ID,ph.DATE_LIV,ph.DEPOT_ID,ph.EXCEPTION,
           ph.WEIGHT,ph.LENGTH,ph.WIDTH,ph.HEIGHT,
           ROW_NUMBER() OVER(
               PARTITION BY ph.PARCEL_ID
               ORDER BY CASE ph.EXCEPTION WHEN 903 THEN 0 ELSE 1 END,
                        ph.DATE_LIV DESC,ph.PARCEL_HISTORY_ID DESC
           ) rn
    FROM parcel_history PARTITION (p2026) ph
    JOIN first_qc q ON q.PARCEL_ID=ph.PARCEL_ID
      AND (ph.DATE_LIV<q.DATE_LIV OR (ph.DATE_LIV=q.DATE_LIV AND ph.PARCEL_HISTORY_ID<q.PARCEL_HISTORY_ID))
    WHERE COALESCE(ph.VOID,0)=0 AND ph.EXCEPTION IN (903,901)
)
SELECT c.PARCEL_ID,p.DATE_LIV prior_scan,p.DEPOT_ID,p.EXCEPTION,
       p.WEIGHT,p.LENGTH,p.WIDTH,p.HEIGHT
FROM code25 c
LEFT JOIN prior_ranked p ON p.PARCEL_ID=c.PARCEL_ID AND p.rn=1
ORDER BY c.PARCEL_ID;
