SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA=DATABASE()
  AND TABLE_NAME IN ('parcel','parcel_history','shipment','manifest')
  AND (COLUMN_NAME LIKE '%DEPOT%' OR COLUMN_NAME LIKE '%DEST%' OR COLUMN_NAME LIKE '%TERMINAL%')
ORDER BY TABLE_NAME,ORDINAL_POSITION;

