SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA=DATABASE()
  AND (TABLE_NAME LIKE '%depot%' OR TABLE_NAME LIKE '%terminal%')
ORDER BY TABLE_NAME,ORDINAL_POSITION;

