SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA=DATABASE()
  AND TABLE_NAME LIKE '%route%'
  AND (COLUMN_NAME LIKE '%ROUTE%' OR COLUMN_NAME LIKE '%DEPOT%' OR COLUMN_NAME LIKE '%NAME%')
ORDER BY TABLE_NAME,ORDINAL_POSITION;

