SELECT ORDINAL_POSITION,COLUMN_NAME,DATA_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='shipment'
  AND (COLUMN_NAME LIKE '%DEPOT%' OR COLUMN_NAME LIKE '%ROUTE%' OR COLUMN_NAME LIKE '%SECTOR%'
       OR COLUMN_NAME LIKE '%ORIG%' OR COLUMN_NAME LIKE '%DEST%' OR COLUMN_NAME LIKE '%INTERNAL%')
ORDER BY ORDINAL_POSITION;

