SELECT
    SOURCE_ID,
    COUNT(*) AS passages,
    COUNT(DISTINCT PARCEL_ID) AS colis_uniques,
    MIN(DATE_LIV) AS premier,
    MAX(DATE_LIV) AS dernier
FROM parcel_history
WHERE EXCEPTION = 903
  AND SOURCE_TYPE = 200
  AND DEPOT_ID = 1
  AND PARCEL_ID IS NOT NULL
  AND PARCEL_ID <> 0
  AND COALESCE(VOID, 0) = 0
  AND DATE_INSERT >= CURDATE() + INTERVAL 15 HOUR
  AND DATE_INSERT < CURDATE() + INTERVAL 1 DAY
  AND DATE_LIV >= CURDATE() + INTERVAL 16 HOUR
  AND DATE_LIV < CURDATE() + INTERVAL 1 DAY
GROUP BY SOURCE_ID
ORDER BY SOURCE_ID;
