name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker information
        run: |
          docker --version
          docker compose version

      - name: Deploy
        run: |
          docker compose pull
          docker compose up -d --remove-orphans

      - name: Status
        run: |
          docker compose ps
